# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "anyio" = super.buildPythonPackage rec {
    pname = "anyio";
    version = "4.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/0e/27be9fdef66e72d64c0cdc3cc2823101b80585f8119b5c112c2e8f5f7dab/anyio-4.12.1-py3-none-any.whl";
      sha256 = "0v5b0sv3vb6n3c1vlhpcxpgz2xyjxs5pnriw1al0l57whj4841fl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."exceptiongroup"
      self."idna"
      self."typing-extensions"
    ];
  };
  "argon2-cffi" = super.buildPythonPackage rec {
    pname = "argon2-cffi";
    version = "25.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4f/d3/a8b22fa575b297cd6e3e3b0155c7e25db170edf1c74783d6a31a2490b8d9/argon2_cffi-25.1.0-py3-none-any.whl";
      sha256 = "0hap7m8vl5hfybh549lscsm1kwiifap08djaxfvcq3rrvdsb1j7x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argon2-cffi-bindings"
    ];
  };
  "argon2-cffi-bindings" = super.buildPythonPackage rec {
    pname = "argon2-cffi-bindings";
    version = "25.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/2d/db8af0df73c1cf454f71b2bbe5e356b8c1f8041c979f505b3d3186e520a9/argon2_cffi_bindings-25.1.0.tar.gz";
      sha256 = "179256zsrh5c51zmv9k1sc9p102j152nzxqgwhhdhmadxbkg6mxr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."setuptools-scm"
      self."cffi"
      self."cffi"
    ];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "asttokens" = super.buildPythonPackage rec {
    pname = "asttokens";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/39/e7eaf1799466a4aef85b6a4fe7bd175ad2b1c6345066aa33f1f58d4b18d0/asttokens-3.0.1-py3-none-any.whl";
      sha256 = "0slp1zsc1xqpnpsz3fc7wjc87ij6j3hjbsmgxr80lb9wyk0fp8qm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "async-lru" = super.buildPythonPackage rec {
    pname = "async-lru";
    version = "2.0.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/49/d10027df9fce941cb8184e78a02857af36360d33e1721df81c5ed2179a1a/async_lru-2.0.5-py3-none-any.whl";
      sha256 = "0hwr5kjqs4yr19nkvh470kphvx55f5rnjcjr6h6k2196im6l15db";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "26.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/b4/17d4b0b2a2dc85a6df63d1157e028ed19f90d4cd97c36717afef2bc2f395/attrs-26.1.0-py3-none-any.whl";
      sha256 = "02f37822ygdqm0vhl9id7gkg8dnw5pk1zrx47hrxkfnz295aliy6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "babel" = super.buildPythonPackage rec {
    pname = "babel";
    version = "2.18.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/f5/21d2de20e8b8b0408f0681956ca2c69f1320a3848ac50e6e7f39c6159675/babel-2.18.0-py3-none-any.whl";
      sha256 = "0ddsmvqr4708x75ci6n51723020dl3106y8x1iiskff2fyr25d72";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "beautifulsoup4" = super.buildPythonPackage rec {
    pname = "beautifulsoup4";
    version = "4.14.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/39/47f9197bdd44df24d67ac8893641e16f386c984a0619ef2ee4c51fbbc019/beautifulsoup4-4.14.3-py3-none-any.whl";
      sha256 = "1frmlw1wgrxrxjjk3li82j9xm61fb08a6avkay6svrh297jby609";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."soupsieve"
      self."typing-extensions"
    ];
  };
  "bleach" = super.buildPythonPackage rec {
    pname = "bleach";
    version = "6.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/55/96142937f66150805c25c4d0f31ee4132fd33497753400734f9dfdcbdc66/bleach-6.2.0-py3-none-any.whl";
      sha256 = "0phyydixsbs39vd59x9nczgjbqgibz9xiz3qslpx5hx7jxh9qz8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."tinycss2"
      self."webencodings"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2026.4.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/30/7cd8fdcdfbc5b869528b079bfb76dcdf6056b1a2097a662e5e8c04f42965/certifi-2026.4.22-py3-none-any.whl";
      sha256 = "0jhw3fii7fyxvbmy9pgcfbzr511w0b8qh0wvs8c27fl8iw623ciw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/56/b1ba7935a17738ae8453301356628e8147c79dbb825bcbc73dc7401f9846/cffi-2.0.0.tar.gz";
      sha256 = "0aambnn8q1jcyshfs002lapi90nypn6h9bh1c3iry4r1j28bbla4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/a1/67fe25fac3c7642725500a3f6cfe5821ad557c3abb11c9d20d12c7008d3e/charset_normalizer-3.4.7.tar.gz";
      sha256 = "1r89l1xvkal0gm7pn4dwalgb62bv7qvd81q4ym5im8cqbygdp2df";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "comm" = super.buildPythonPackage rec {
    pname = "comm";
    version = "0.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/97/891a0971e1e4a8c5d2b20bbe0e524dc04548d2307fee33cdeba148fd4fc7/comm-0.2.3-py3-none-any.whl";
      sha256 = "05wl9172ypx8hscbxh8rckf3pm5b3dqw3l9hbc4lzw7pflfxj5f6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "contourpy" = super.buildPythonPackage rec {
    pname = "contourpy";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/f6/31a8f28b4a2a4fa0e01085e542f3081ab0588eff8e589d39d775172c9792/contourpy-1.3.0.tar.gz";
      sha256 = "191q34pbbm984jvlv462jaw9dnb28ddckl7g4yqzza0pfyqhvykz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "cycler" = super.buildPythonPackage rec {
    pname = "cycler";
    version = "0.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl";
      sha256 = "0c0d9s2mmb6b7jnbhnclb5017rbjb530i62jc50n9n12yb7zgkl5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "debugpy" = super.buildPythonPackage rec {
    pname = "debugpy";
    version = "1.8.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/c3/7f67dea8ccf8fdcb9c99033bbe3e90b9e7395415843accb81428c441be2d/debugpy-1.8.20-py2.py3-none-any.whl";
      sha256 = "1mslgs8dkj58m7v0kz8m5xivkli9hf7s9jkal1jhdq1vmvcvxsav";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "5.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/8c/f3147f5c4b73e7550fe5f9352eaa956ae838d5c51eb58e7a25b9f3e2643b/decorator-5.2.1-py3-none-any.whl";
      sha256 = "0jp0r2hhdhdgfrmdfb191qj0kz02cm60ii5w78mjv7idb90vn5nk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "defusedxml" = super.buildPythonPackage rec {
    pname = "defusedxml";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl";
      sha256 = "0qca37v5iv0304hrl9pzad4jpnxfrnv449cyi768c0kp53jfflm3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/0e/97c33bf5009bdbac74fd2beace167cab3f978feb69cc36f1ef79360d6c4e/exceptiongroup-1.3.1-py3-none-any.whl";
      sha256 = "161mfwnghxs52jjvffv3zgglw30xf2jx71s976c1wy3ns8xrm8x7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "executing" = super.buildPythonPackage rec {
    pname = "executing";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/ea/53f2148663b321f21b5a606bd5f191517cf40b7072c0497d3c92c4a13b1e/executing-2.2.1-py2.py3-none-any.whl";
      sha256 = "05r09dd44315zy7f1d9zy8fshr2cqz66gcav55ypfk9b8p9l61kn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fastjsonschema" = super.buildPythonPackage rec {
    pname = "fastjsonschema";
    version = "2.21.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/a8/20d0723294217e47de6d9e2e40fd4a9d2f7c4b6ef974babd482a59743694/fastjsonschema-2.21.2-py3-none-any.whl";
      sha256 = "0qz4fxmll0jw5krp4w81aasj6qn337lg8jz5wan5qv58s0i72y8w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fonttools" = super.buildPythonPackage rec {
    pname = "fonttools";
    version = "4.60.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3e/c4/db6a7b5eb0656534c3aa2596c2c5e18830d74f1b9aa5aa8a7dff63a0b11d/fonttools-4.60.2.tar.gz";
      sha256 = "0b6903wgv9nysgsjxhilnx5c2xnb57agiv0abdlgrssmn7k555fj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "h11" = super.buildPythonPackage rec {
    pname = "h11";
    version = "0.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/4b/29cac41a4d98d144bf5f6d33995617b185d14b22401f75ca86f384e87ff1/h11-0.16.0-py3-none-any.whl";
      sha256 = "11kcrcqlp99djdajvrnsngzn883pqbcs3z9jb7v3ppi2fnz8pkv3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "httpcore" = super.buildPythonPackage rec {
    pname = "httpcore";
    version = "1.0.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/f5/f66802a942d491edb555dd61e3a9961140fd64c90bce1eafd741609d334d/httpcore-1.0.9-py3-none-any.whl";
      sha256 = "0mdzl73j982lss7w7a20ns2482xlfa82644qxjfzqs06li30fh1d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."h11"
    ];
  };
  "httpx" = super.buildPythonPackage rec {
    pname = "httpx";
    version = "0.28.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl";
      sha256 = "1barpaw8as8xb7b2bsmzdmdbq5nqljlq5jhlz3xcgy0hq76gq2fr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."certifi"
      self."httpcore"
      self."idna"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/13/ad7d7ca3808a898b4612b6fe93cde56b53f3034dcde235acb1f0e1df24c6/idna-3.13-py3-none-any.whl";
      sha256 = "1cwbphsn2sdp5qimzzbzqv1njasmql2a5jyyfgkrra94w76s0bl9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "imageio" = super.buildPythonPackage rec {
    pname = "imageio";
    version = "2.37.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/fe/301e0936b79bcab4cacc7548bf2853fc28dced0a578bab1f7ef53c9aa75b/imageio-2.37.2-py3-none-any.whl";
      sha256 = "16qbpnjxhwvjwm9hmi1klchi054zss73amz47p01imrm0frdz6md";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
      self."pillow"
    ];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "8.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/5e/f8e9a1d23b9c20a551a8a02ea3637b4642e22c2626e3a13a9a29cdea99eb/importlib_metadata-8.7.1-py3-none-any.whl";
      sha256 = "0lb12x9kn1j429c9khlbibr4qqsssyav1yqy0yar8j5a3nzq07ss";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "importlib-resources" = super.buildPythonPackage rec {
    pname = "importlib-resources";
    version = "6.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/ed/1f1afb2e9e7f38a545d628f864d562a5ae64fe6f7a10e28ffb9b185b4e89/importlib_resources-6.5.2-py3-none-any.whl";
      sha256 = "1v6cc2kxi319k1d0k77psninkv8wflk83jval1kqpir8xp1zv73q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "ipykernel" = super.buildPythonPackage rec {
    pname = "ipykernel";
    version = "6.31.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/d8/502954a4ec0efcf264f99b65b41c3c54e65a647d9f0d6f62cd02227d242c/ipykernel-6.31.0-py3-none-any.whl";
      sha256 = "1bwlik6hc12sgms4f8gqdzxcb9qzh3dg237bw1q7lwpddipkirdb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."comm"
      self."debugpy"
      self."ipython"
      self."jupyter-client"
      self."jupyter-core"
      self."matplotlib-inline"
      self."nest-asyncio"
      self."packaging"
      self."psutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "ipython" = super.buildPythonPackage rec {
    pname = "ipython";
    version = "8.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/6b/d9fdcdef2eb6a23f391251fde8781c38d42acd82abe84d054cb74f7863b0/ipython-8.18.1-py3-none-any.whl";
      sha256 = "15x3kblhabwy240r4ja7sq5ch2m9m8lqlzqpq5g9b09dswcp89p8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."exceptiongroup"
      self."jedi"
      self."matplotlib-inline"
      self."pexpect"
      self."prompt-toolkit"
      self."pygments"
      self."stack-data"
      self."traitlets"
      self."typing-extensions"
    ];
  };
  "ipywidgets" = super.buildPythonPackage rec {
    pname = "ipywidgets";
    version = "8.1.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/6d/0d9848617b9f753b87f214f1c682592f7ca42de085f564352f10f0843026/ipywidgets-8.1.8-py3-none-any.whl";
      sha256 = "07ljqb0l7nwrxzsz1hc9vjsim0lgnn0i2yzni27k6jkhxmxadb7c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."comm"
      self."ipython"
      self."jupyterlab-widgets"
      self."traitlets"
      self."widgetsnbextension"
    ];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/5a/9cac0c82afec3d09ccd97c8b6502d48f165f9124db81b4bcb90b4af974ee/jedi-0.19.2-py2.py3-none-any.whl";
      sha256 = "1fdmxpv6wnyf7kg88irbyzd7925m7k4a70bnbkz5f3s9x2yj5vx8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl";
      sha256 = "0rrgdp707wfs11wk8prswvx6ma418sk16z6xql9hqba93x2y9v45";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markupsafe"
    ];
  };
  "json5" = super.buildPythonPackage rec {
    pname = "json5";
    version = "0.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b8/42/cf027b4ac873b076189d935b135397675dac80cb29acb13e1ab86ad6c631/json5-0.14.0-py3-none-any.whl";
      sha256 = "0fpgpag87gva4wncik52rsd9nfi73lqy34lcxdw12sq7mcdqdksn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "4.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/9c/8c95d856233c1f82500c2450b8c68576b4cf1c871db3afac5c34ff84e6fd/jsonschema-4.25.1-py3-none-any.whl";
      sha256 = "0qqa4cajkwl78nx69fgkzi682r6389ila79m218igis5wdlh3fiz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."jsonschema-specifications"
      self."referencing"
      self."rpds-py"
    ];
  };
  "jsonschema-specifications" = super.buildPythonPackage rec {
    pname = "jsonschema-specifications";
    version = "2025.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/45/1a4ed80516f02155c51f51e8cedb3c1902296743db0bbc66608a0db2814f/jsonschema_specifications-2025.9.1-py3-none-any.whl";
      sha256 = "1zn61hhky48v2lw2h3qan2cgy6x4m3yjji54mkn7dvhi7bp2z04q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."referencing"
    ];
  };
  "jupyter" = super.buildPythonPackage rec {
    pname = "jupyter";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/64/285f20a31679bf547b75602702f7800e74dbabae36ef324f716c02804753/jupyter-1.1.1-py2.py3-none-any.whl";
      sha256 = "10ycyzipilqah806qnn6dbqzhnp9lirh7rmv4jdl6rdg48y56nbs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."jupyterlab"
      self."nbconvert"
      self."notebook"
    ];
  };
  "jupyter-client" = super.buildPythonPackage rec {
    pname = "jupyter-client";
    version = "8.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/85/b0394e0b6fcccd2c1eeefc230978a6f8cb0c5df1e4cd3e7625735a0d7d1e/jupyter_client-8.6.3-py3-none-any.whl";
      sha256 = "0gzjx04cpwm59zlha2ac9d18bbzk23s1aa9nqdd90ifchv4rr8g8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-console" = super.buildPythonPackage rec {
    pname = "jupyter-console";
    version = "6.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/77/71d78d58f15c22db16328a476426f7ac4a60d3a5a7ba3b9627ee2f7903d4/jupyter_console-6.6.3-py3-none-any.whl";
      sha256 = "11946pjkvh6s1xbpf49ldwdsdnm9lkwws2szsbdgz4nckx03779h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."jupyter-core"
      self."prompt-toolkit"
      self."pygments"
      self."pyzmq"
      self."traitlets"
    ];
  };
  "jupyter-core" = super.buildPythonPackage rec {
    pname = "jupyter-core";
    version = "5.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/57/6bffd4b20b88da3800c5d691e0337761576ee688eb01299eae865689d2df/jupyter_core-5.8.1-py3-none-any.whl";
      sha256 = "1l3393i0cmxp92lyh1l46nd49i840x0yplny709kzd8gr67jd3f2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."platformdirs"
      self."traitlets"
    ];
  };
  "jupyter-events" = super.buildPythonPackage rec {
    pname = "jupyter-events";
    version = "0.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/6c/6fcde0c8f616ed360ffd3587f7db9e225a7e62b583a04494d2f069cf64ea/jupyter_events-0.12.1-py3-none-any.whl";
      sha256 = "1kwbxj9jsz07gcg52gw9zq0m6nqc86kpryjjv8kscdzmad95hrn3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jsonschema"
      self."packaging"
      self."python-json-logger"
      self."pyyaml"
      self."referencing"
      self."rfc3339-validator"
      self."rfc3986-validator"
      self."traitlets"
    ];
  };
  "jupyter-lsp" = super.buildPythonPackage rec {
    pname = "jupyter-lsp";
    version = "2.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/e8/9d61dcbd1dce8ef418f06befd4ac084b4720429c26b0b1222bc218685eff/jupyter_lsp-2.3.1-py3-none-any.whl";
      sha256 = "10fvv915wz0g5dw9lvq3adqf6zxgxwp4ym80ch4z6pz86kc59fbi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
      self."jupyter-server"
    ];
  };
  "jupyter-server" = super.buildPythonPackage rec {
    pname = "jupyter-server";
    version = "2.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/80/a24767e6ca280f5a49525d987bf3e4d7552bf67c8be07e8ccf20271f8568/jupyter_server-2.17.0-py3-none-any.whl";
      sha256 = "0gz1f0cfxqdxvqj0bmc2zxb21krcny0rncky63nm27r5niyrrjz8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."argon2-cffi"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."jupyter-events"
      self."jupyter-server-terminals"
      self."nbconvert"
      self."nbformat"
      self."overrides"
      self."packaging"
      self."prometheus-client"
      self."pyzmq"
      self."send2trash"
      self."terminado"
      self."tornado"
      self."traitlets"
      self."websocket-client"
    ];
  };
  "jupyter-server-terminals" = super.buildPythonPackage rec {
    pname = "jupyter-server-terminals";
    version = "0.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/2d/6674563f71c6320841fc300911a55143925112a72a883e2ca71fba4c618d/jupyter_server_terminals-0.5.4-py3-none-any.whl";
      sha256 = "053x03i0hmvanvf7ix96ar9csqaslm8bxri07dzvr02aqwzkbgjm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."terminado"
    ];
  };
  "jupyterlab" = super.buildPythonPackage rec {
    pname = "jupyterlab";
    version = "4.5.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/1b/dad6fdcc658ed7af26fdf3841e7394072c9549a8b896c381ab49dd11e2d9/jupyterlab-4.5.6-py3-none-any.whl";
      sha256 = "1075s76sjla3damlxmmfk58gf926naaqw3wf6j9rjkdahg4dmcyn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-lru"
      self."httpx"
      self."importlib-metadata"
      self."ipykernel"
      self."jinja2"
      self."jupyter-core"
      self."jupyter-lsp"
      self."jupyter-server"
      self."jupyterlab-server"
      self."notebook-shim"
      self."packaging"
      self."setuptools"
      self."tomli"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyterlab-pygments" = super.buildPythonPackage rec {
    pname = "jupyterlab-pygments";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/dd/ead9d8ea85bf202d90cc513b533f9c363121c7792674f78e0d8a854b63b4/jupyterlab_pygments-0.3.0-py3-none-any.whl";
      sha256 = "1017hjwa2qi46bb1y98vpcjc8pgwmsbrkagijf31vnki1418j6l4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jupyterlab-server" = super.buildPythonPackage rec {
    pname = "jupyterlab-server";
    version = "2.28.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/07/a000fe835f76b7e1143242ab1122e6362ef1c03f23f83a045c38859c2ae0/jupyterlab_server-2.28.0-py3-none-any.whl";
      sha256 = "0s39a0cdsxsm4fzkd1wb1r320vbx8qi0zj5v5cqlvwywiwa5ndg4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."babel"
      self."importlib-metadata"
      self."jinja2"
      self."json5"
      self."jsonschema"
      self."jupyter-server"
      self."packaging"
      self."requests"
    ];
  };
  "jupyterlab-widgets" = super.buildPythonPackage rec {
    pname = "jupyterlab-widgets";
    version = "3.0.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ab/b5/36c712098e6191d1b4e349304ef73a8d06aed77e56ceaac8c0a306c7bda1/jupyterlab_widgets-3.0.16-py3-none-any.whl";
      sha256 = "1y7cyy00r0qwg00ba9lr5niwfhx2394dpr4qj5az4b22qvckdyj5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kiwisolver" = super.buildPythonPackage rec {
    pname = "kiwisolver";
    version = "1.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/4d/2255e1c76304cbd60b48cee302b66d1dde4468dc5b1160e4b7cb43778f2a/kiwisolver-1.4.7.tar.gz";
      sha256 = "0q0ak10hwlyza21qhjkfq97xpaixb337q0fkhnvgf1vipn0zz4wq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "laserbeamsize" = super.buildPythonPackage rec {
    pname = "laserbeamsize";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/82/e6830f099b794f18a484e476e40f4764a4a9d53bf2181785602a1946b2d4/laserbeamsize-2.3.0-py3-none-any.whl";
      sha256 = "1gkr283y8ky2pgmqm2gpknkv41sf3fp4a899khpp2gpnw1xm45ak";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."matplotlib"
      self."numpy"
      self."scipy"
    ];
  };
  "markupsafe" = super.buildPythonPackage rec {
    pname = "markupsafe";
    version = "3.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/99/7690b6d4034fffd95959cbe0c02de8deb3098cc577c67bb6a24fe5d7caa7/markupsafe-3.0.3.tar.gz";
      sha256 = "160npsg7jh6mbiwy23xm9aqcxgcn0wl33hgx42rmfr2biy09a9kj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "matplotlib" = super.buildPythonPackage rec {
    pname = "matplotlib";
    version = "3.9.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/17/1747b4154034befd0ed33b52538f5eb7752d05bb51c5e2a31470c3bc7d52/matplotlib-3.9.4.tar.gz";
      sha256 = "1hqvlhxh4slh1g3b2p989f0q6gng0ax6z2psxmpxrjwkffzfh00y";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."contourpy"
      self."cycler"
      self."fonttools"
      self."importlib-resources"
      self."kiwisolver"
      self."numpy"
      self."packaging"
      self."pillow"
      self."pyparsing"
      self."python-dateutil"
    ];
  };
  "matplotlib-inline" = super.buildPythonPackage rec {
    pname = "matplotlib-inline";
    version = "0.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/33/ee4519fa02ed11a94aef9559552f3b17bb863f2ecfe1a35dc7f548cde231/matplotlib_inline-0.2.1-py3-none-any.whl";
      sha256 = "0xhaf7skkvvnx6ibplaw45zc9a99xpbflkymm405w256dcayav6m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "mistune" = super.buildPythonPackage rec {
    pname = "mistune";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9b/f7/4a5e785ec9fbd65146a27b6b70b6cdc161a66f2024e4b04ac06a67f5578b/mistune-3.2.0-py3-none-any.whl";
      sha256 = "1qgfs11bxx6kbv1wczlqi714rqz0a42miilk8fwid1n7lclwdggy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "nbclient" = super.buildPythonPackage rec {
    pname = "nbclient";
    version = "0.10.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/34/6d/e7fa07f03a4a7b221d94b4d586edb754a9b0dc3c9e2c93353e9fa4e0d117/nbclient-0.10.2-py3-none-any.whl";
      sha256 = "0gfwxam1ybhzs2zs8hj3yfc552iiwi3mb5dppvx2fjlbg0gf3zjg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-client"
      self."jupyter-core"
      self."nbformat"
      self."traitlets"
    ];
  };
  "nbconvert" = super.buildPythonPackage rec {
    pname = "nbconvert";
    version = "7.17.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/f8/bb0a9d5f46819c821dc1f004aa2cc29b1d91453297dbf5ff20470f00f193/nbconvert-7.17.1-py3-none-any.whl";
      sha256 = "1j77ndd4j9bhpb0kpcyaxj4jnpr8irjryc83zlgvzrrmnj3w11da";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."beautifulsoup4"
      self."bleach"
      self."defusedxml"
      self."importlib-metadata"
      self."jinja2"
      self."jupyter-core"
      self."jupyterlab-pygments"
      self."markupsafe"
      self."mistune"
      self."nbclient"
      self."nbformat"
      self."packaging"
      self."pandocfilters"
      self."pygments"
      self."traitlets"
    ];
  };
  "nbformat" = super.buildPythonPackage rec {
    pname = "nbformat";
    version = "5.10.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/82/0340caa499416c78e5d8f5f05947ae4bc3cba53c9f038ab6e9ed964e22f1/nbformat-5.10.4-py3-none-any.whl";
      sha256 = "02r0j645i0cygc4assf2zvj805gj3bdsfblqyfdjjjyazg4dcj1v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."fastjsonschema"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
  };
  "nest-asyncio" = super.buildPythonPackage rec {
    pname = "nest-asyncio";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/c4/c2971a3ba4c6103a3d10c4b0f24f461ddc027f0f09763220cf35ca1401b3/nest_asyncio-1.6.0-py3-none-any.whl";
      sha256 = "071fhnqhaagz3bhcl0qpslsjyarfqrjyyxq40n0pr2aydgynxbw7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "notebook" = super.buildPythonPackage rec {
    pname = "notebook";
    version = "7.5.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/aa/cbd1deb9f07446241e88f8d5fecccd95b249bca0b4e5482214a4d1714c49/notebook-7.5.5-py3-none-any.whl";
      sha256 = "1f52chkxmagx02kf4svqyfxza40c5sccm412yy3jwnd6xyz4vhd7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-server"
      self."jupyterlab"
      self."jupyterlab-server"
      self."notebook-shim"
      self."tornado"
    ];
  };
  "notebook-shim" = super.buildPythonPackage rec {
    pname = "notebook-shim";
    version = "0.2.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/33/bd5b9137445ea4b680023eb0469b2bb969d61303dedb2aac6560ff3d14a1/notebook_shim-0.2.4-py3-none-any.whl";
      sha256 = "1vqw1rb8cs8934s9lzknd2qcwk56xmqydjnb9h3jm26wx7j5n6j1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-server"
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/75/10dd1f8116a8b796cb2c737b674e02d02e80454bda953fa7e65d8c12b016/numpy-2.0.2.tar.gz";
      sha256 = "0y3fcd268cnrc8ipcmj1c082an4j4a4wj3dbcjlf500qxryrhg48";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "overrides" = super.buildPythonPackage rec {
    pname = "overrides";
    version = "7.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/ab/fc8290c6a4c722e5514d80f62b2dc4c4df1a68a41d1364e625c35990fcf3/overrides-7.7.0-py3-none-any.whl";
      sha256 = "0jby1p32cxnwqpwpw8hhypcx9simddwxh2xplz0y9f3q5w39vvf7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "26.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/c2/920ef838e2f0028c8262f16101ec09ebd5969864e5a64c4c05fad0617c56/packaging-26.1-py3-none-any.whl";
      sha256 = "0bw0lsmq3944757fj6aav5qbcrxggrcfwbpd1hg4jpi8qrlhd72x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pandocfilters" = super.buildPythonPackage rec {
    pname = "pandocfilters";
    version = "1.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/af/4fbc8cab944db5d21b7e2a5b8e9211a03a79852b1157e2c102fcc61ac440/pandocfilters-1.5.1-py2.py3-none-any.whl";
      sha256 = "1g725liycpvgilk5pa25anz1nwyiwmbz31bm4skv1kd90hl3iglk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.8.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/61/fae042894f4296ec49e3f193aff5d7c18440da9e48102c3315e1bc4519a7/parso-0.8.6-py2.py3-none-any.whl";
      sha256 = "1zxsh3rqpw1v3mkr5ii97c1hzc2cb0jqh94p46aw99bh1f09ym1c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/c3/059298687310d527a58bb01f3b1965787ee3b40dce76752eda8b44e9a2c5/pexpect-4.9.0-py2.py3-none-any.whl";
      sha256 = "08rm4mza8w0f45hd1qd72a9cyapp1bn6qciyvki6p4z4h3hd2dkj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "11.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/0d/d0d6dea55cd152ce3d6767bb38a8fc10e33796ba4ba210cbab9354b6d238/pillow-11.3.0.tar.gz";
      sha256 = "08zmx0sy0xh6km2ll5l7psdn9l107vamm7i0ns8j02ydhrsywa1q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "platformdirs" = super.buildPythonPackage rec {
    pname = "platformdirs";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/40/4b/2028861e724d3bd36227adfa20d3fd24c3fc6d52032f4a93c133be5d17ce/platformdirs-4.4.0-py3-none-any.whl";
      sha256 = "11ccjmjxp9i5ivcjdv1q7wsnab8smwppbcsxgb6qfljfy91igl5b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prometheus-client" = super.buildPythonPackage rec {
    pname = "prometheus-client";
    version = "0.25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/9b/d4b1e644385499c8346fa9b622a3f030dce14cd6ef8a1871c221a17a67e7/prometheus_client-0.25.0-py3-none-any.whl";
      sha256 = "1lgyb682ghp3cilahbqsdkyp8zw0yf1gh3axh0qc4vls6jgcibnm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "3.0.52";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/03/0d3ce49e2505ae70cf43bc5bb3033955d2fc9f932163e84dc0779cc47f48/prompt_toolkit-3.0.52-py3-none-any.whl";
      sha256 = "0mcrl7bgr58hqavkkp32ly8ln16civbdhnny8x1jhcxx7fd67b4s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wcwidth"
    ];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "7.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/c6/d1ddf4abb55e93cebc4f2ed8b5d6dbad109ecb8d63748dd2b20ab5e57ebe/psutil-7.2.2.tar.gz";
      sha256 = "0wlkyn4bpd40dnhxdf1v56y3vhzmlpdciwa7sm7k9bq6skwgaih7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl";
      sha256 = "0dgg5x4nvdpfiz552diy11xg72y14s38hjz9qxygafnfgybg6hab";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pure-eval" = super.buildPythonPackage rec {
    pname = "pure-eval";
    version = "0.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8e/37/efad0257dc6e593a18957422533ff0f87ede7c9c6ea010a2177d738fb82f/pure_eval-0.2.3-py3-none-any.whl";
      sha256 = "1l70fk4fvjwqra0v19qzj0ha8fkcy0kkwrdf33c1ilmkcxdy7f0x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.23";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/e3/59cd50310fc9b59512193629e1984c1f95e5c8ae6e5d8c69532ccc65a7fe/pycparser-2.23-py3-none-any.whl";
      sha256 = "0d2r3bw5mbqdan521f1xxqmsz7qakrr07b09mff4flxdzg9yiip5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.20.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/7e/a72dd26f3b0f4f2bf1dd8923c85f7ceb43172af56d63c7383eb62b332364/pygments-2.20.0-py3-none-any.whl";
      sha256 = "0xh1dna5yy5lixlx97mmz3i4cfy0g9nxhsfil8iqmligsiny5ac1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/bd/c038d7cc38edc1aa5bf91ab8068b63d4308c66c4c8bb3cbba7dfbc049f9c/pyparsing-3.3.2-py3-none-any.whl";
      sha256 = "07cid767w02ss3kfbqj0kj1jf0sg3rx28zjq24j7x3chpm4a22w5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-json-logger" = super.buildPythonPackage rec {
    pname = "python-json-logger";
    version = "4.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/e5/fecf13f06e5e5f67e8837d777d1bc43fac0ed2b77a676804df5c34744727/python_json_logger-4.0.0-py3-none-any.whl";
      sha256 = "1qm1bcf3hbn9mr9rjk03ash5z7ia1zsra0qqqx6al4x8yvdcj2dg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz";
      sha256 = "03qrhk1vz2g12xgy9mdr4p3ibvxprch710gq9kxj5pr16hvj6rnp";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "27.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/0b/3c9baedbdf613ecaa7aa07027780b8867f57b6293b6ee50de316c9f3222b/pyzmq-27.1.0.tar.gz";
      sha256 = "0h5mdlphfj19vzphi34p0l5c83s6rvf1fi5zvnvasma4skina1xc";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "referencing" = super.buildPythonPackage rec {
    pname = "referencing";
    version = "0.36.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/b1/3baf80dc6d2b7bc27a95a67752d0208e410351e3feb4eb78de5f77454d8d/referencing-0.36.2-py3-none-any.whl";
      sha256 = "1l6wjikqrc4bxbi6hj88rspvxcsqq6shxylgdplpsp4bpzdrlsg8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."rpds-py"
      self."typing-extensions"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl";
      sha256 = "1dpz38b6lnn8fcad7kfiagagbc3djy3f35a24qrdakx36x3gjqi4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "rfc3339-validator" = super.buildPythonPackage rec {
    pname = "rfc3339-validator";
    version = "0.1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/44/4e421b96b67b2daff264473f7465db72fbdf36a07e05494f50300cc7b0c6/rfc3339_validator-0.1.4-py2.py3-none-any.whl";
      sha256 = "1ylifxz5fn987hx3sk8asl29rcr4648wfvp3m4yq5vqlv8gfrxi4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "rfc3986-validator" = super.buildPythonPackage rec {
    pname = "rfc3986-validator";
    version = "0.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/51/17023c0f8f1869d8806b979a2bffa3f861f26a3f1a66b094288323fba52f/rfc3986_validator-0.1.1-py2.py3-none-any.whl";
      sha256 = "1adz53sh2vk34zis232i3fixvnymp4v96dh68c5rfngl5r1mq8rg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "rpds-py" = super.buildPythonPackage rec {
    pname = "rpds-py";
    version = "0.27.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/dd/2c0cbe774744272b0ae725f44032c77bdcab6e8bcf544bffa3b6e70c8dba/rpds_py-0.27.1.tar.gz";
      sha256 = "1y0hbaygifsbqynmnmhyc01q5aw6lpv2pn6yrg67l2yif4qwg896";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "scipy" = super.buildPythonPackage rec {
    pname = "scipy";
    version = "1.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/00/48c2f661e2816ccf2ecd77982f6605b2950afe60f60a52b4cbbc2504aa8f/scipy-1.13.1.tar.gz";
      sha256 = "0g7dfjw18c00hh5qq6wkzh01iid8239vnp0mlvbdy21b66h8fnh9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "send2trash" = super.buildPythonPackage rec {
    pname = "send2trash";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/78/504fdd027da3b84ff1aecd9f6957e65f35134534ccc6da8628eb71e76d3f/send2trash-2.1.0-py3-none-any.whl";
      sha256 = "0g47kbz4kn2a3i2n2wm8ybmly6l38khsgnm6dbg25fynwq9g38hd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "setuptools-scm" = super.buildPythonPackage rec {
    pname = "setuptools-scm";
    version = "9.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/ea/ac2bf868899d0d2e82ef72d350d97a846110c709bacf2d968431576ca915/setuptools_scm-9.2.2-py3-none-any.whl";
      sha256 = "1xxf04c6gmhxbzy0fj6mflvw7l4mjcbrnhjkwsq7rfmi596zis1h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
      self."setuptools"
      self."tomli"
      self."typing-extensions"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "soupsieve" = super.buildPythonPackage rec {
    pname = "soupsieve";
    version = "2.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/2c/1462b1d0a634697ae9e55b3cecdcb64788e8b7d63f54d923fcd0bb140aed/soupsieve-2.8.3-py3-none-any.whl";
      sha256 = "15asyj8mnm4snxmy7hgzg1claiqn737gyalnqinb1spb9sxg4r7d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "stack-data" = super.buildPythonPackage rec {
    pname = "stack-data";
    version = "0.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl";
      sha256 = "15g627jndkgqp68rz7yxhp5hh6l9m5yxglysrm9hijx44l68wmfm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asttokens"
      self."executing"
      self."pure-eval"
    ];
  };
  "terminado" = super.buildPythonPackage rec {
    pname = "terminado";
    version = "0.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6a/9e/2064975477fdc887e47ad42157e214526dcad8f317a948dee17e1659a62f/terminado-0.18.1-py3-none-any.whl";
      sha256 = "1c6fvh2x778da2j94fcvy9y9gz0s9s0naksihs58ycdv6wdqwim4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
  };
  "tinycss2" = super.buildPythonPackage rec {
    pname = "tinycss2";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/34/ebdc18bae6aa14fbee1a08b63c015c72b64868ff7dae68808ab500c492e2/tinycss2-1.4.0-py3-none-any.whl";
      sha256 = "12aj9j40vnssfyjhbfab77lrdgafvzw1svhcbnqs0pb7nx3wyj9s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."webencodings"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/61/cceae43728b7de99d9b847560c262873a1f6c98202171fd5ed62640b494b/tomli-2.4.1-py3-none-any.whl";
      sha256 = "1zj9ic1361g962pxrrsasn3nb30zimpnb1nb8gd2488k0ac8318d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.5.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/f1/3173dfa4a18db4a9b03e5d55325559dab51ee653763bb8745a75af491286/tornado-6.5.5.tar.gz";
      sha256 = "1s9hilgbj4gr0wprd6vpjqpvgiknxlb595861ksz3mqvm4z8yaqr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "traitlets" = super.buildPythonPackage rec {
    pname = "traitlets";
    version = "5.14.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/c0/8f5d070730d7836adc9c9b6408dec68c6ced86b304a9b26a14df072a6e8c/traitlets-5.14.3-py3-none-any.whl";
      sha256 = "0kxcy67nh9jl2k590c717p5l0rmsb6ksxdqxhg62ivdijziqjkmp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl";
      sha256 = "0j75qhcc0p627f464gd7kjcirdzcga5zl32a0w4ann2phk31kyph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/08/aaaad47bc4e9dc8c725e68f9d04865dbcb2052843ff09c97b08904852d84/urllib3-2.6.3-py3-none-any.whl";
      sha256 = "1m5cn1yd6gvd8dax7fyp36wngx5hlxf25zcvgplb5pskwlij69xz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/5a/199c59e0a824a3db2b89c5d2dade7ab5f9624dbf6448dc291b46d5ec94d3/wcwidth-0.6.0-py3-none-any.whl";
      sha256 = "1bdxzxw19nwc11w3s6vkmpzn8qpvyij4gia6w7w1acsm1d8iwfhs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "webencodings" = super.buildPythonPackage rec {
    pname = "webencodings";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl";
      sha256 = "0y2aa53jkkcszhbbx59z817ywjvy3ah3lavym6bn88n2yc9i5bx0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "websocket-client" = super.buildPythonPackage rec {
    pname = "websocket-client";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/34/db/b10e48aa8fff7407e67470363eac595018441cf32d5e1001567a7aeba5d2/websocket_client-1.9.0-py3-none-any.whl";
      sha256 = "1vy33wffxvi9llq24nlygfsd60xabz621vgnzcg5kvrpa218l95g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "widgetsnbextension" = super.buildPythonPackage rec {
    pname = "widgetsnbextension";
    version = "4.0.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/0e/fa3b193432cfc60c93b42f3be03365f5f909d2b3ea410295cf36df739e31/widgetsnbextension-4.0.15-py3-none-any.whl";
      sha256 = "0rikryf8ja4a4avj6wpxmg4hd6d2hvp4pf3krvcp39a68d770ml1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.23.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/08/8a/0861bec20485572fbddf3dfba2910e38fe249796cb73ecdeb74e07eeb8d3/zipp-3.23.1-py3-none-any.whl";
      sha256 = "1p24whrmdj7syz6npc7dkdz81i1ckxnxia0bnjf0qw2w1b2rcd8b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
